/**
 * seed_invoicing_demo.ts
 * P1 Foundation — Demo seed for 7 SalesTypes (DO NOT AUTO-RUN)
 *
 * PURPOSE:
 *  Creates 7 demo invoices, one per SalesType, to verify the staged migration
 *  (supabase/migrations/20260902000000_invoicing_staged.sql) works end-to-end.
 *
 * USAGE (manual only, after migration + regen):
 *  1. Ensure migration has been applied:
 *     psql $DATABASE_URL -f supabase/migrations/20260902000000_invoicing_staged.sql
 *  2. Regen types (local):
 *     supabase gen types typescript --local > src/integrations/supabase/types.ts
 *  3. Set env: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (or anon with RLS bypass for dev)
 *  4. Run manually:
 *     npx tsx scripts/seed_invoicing_demo.ts
 *     # or: deno run --allow-env --allow-net scripts/seed_invoicing_demo.ts
 *
 * NOTES:
 *  - This file is NOT executed automatically. It is a helper for manual verification.
 *  - Requires existing branches + customers + products. Update IDs via fetchOrCreate below.
 *  - Inserts are minimal (subtotal/tax computed via app gst helpers if available).
 *  - New columns verified: sales_type, is_tax_inclusive, lut_no, supply_class,
 *    transport_details, einvoice_status, eway_status, compliance_json, etc.
 *  - Idempotent guard: invoice_no is generated by DB trigger set_invoice_no();
 *    we leave invoice_no = null and check for duplicate demo batch via compliance_json->>'seed_batch'.
 */

import { createClient } from "@supabase/supabase-js";

// ---------------------------------------------------------------------------
// Expected SalesType values — single source of truth (see src/lib/sales.ts)
// ---------------------------------------------------------------------------
export const EXPECTED_SALES_TYPES = [
  "local_itemwise",
  "local_multirate",
  "local_multirate_cons",
  "local_nil_rated",
  "local_tax_incl",
  "sez_taxable",
  "sez_zero_rated",
] as const;

export type SalesType = (typeof EXPECTED_SALES_TYPES)[number];

export function showExpectedSalesTypes(): void {
  console.log("Expected SalesType values (P1 Foundation — 7 Tally parity):");
  console.table(
    EXPECTED_SALES_TYPES.map((t) => ({
      sales_type: t,
      is_tax_inclusive: t === "local_tax_incl",
      supply_class:
        t === "local_nil_rated" ? "nil" : t === "sez_zero_rated" ? "zero_rated" : null,
      gstr_bucket:
        t === "local_nil_rated"
          ? "Table 8 Nil"
          : t === "sez_zero_rated"
            ? "SEZWOP (LUT)"
            : t === "sez_taxable"
              ? "SEZWP"
              : t === "local_tax_incl"
                ? "B2B regular (incl.)"
                : "B2B regular",
    })),
  );
}

// ---------------------------------------------------------------------------
// Minimal demo transport_details payload (25-field shape, keep most null)
// ---------------------------------------------------------------------------
function demoTransport(suffix: string): Record<string, unknown> {
  return {
    vehicle_no: `MH12AB${suffix.padStart(4, "0")}`,
    transporter_name: "Prokon Demo Transporter",
    transporter_gstin: "27AACCP1234A1Z5",
    transporter_id: null,
    transport_mode: "road",
    distance_km: 120,
    lr_no: `LR-DEMO-${suffix}`,
    lr_date: new Date().toISOString().slice(0, 10),
    ewaybill_no: null,
    ewaybill_date: null,
    ewaybill_valid_till: null,
    driver_name: "Demo Driver",
    driver_mobile: "9876543210",
    place_of_supply: "Maharashtra",
    place_of_supply_code: "27",
    // remaining 10+ fields left as null/empty for P1 verification
    _seed_note: `demo-${suffix}`,
  };
}

// ---------------------------------------------------------------------------
// Main seed — comment out auto-run; export for manual invocation
// ---------------------------------------------------------------------------
export async function seedInvoicingDemo() {
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY;
  if (!url || !key) {
    console.error("Missing SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY (or anon). Aborting.");
    process.exit(1);
  }

  const supabase = createClient(url, key);

  // Resolve required FKs — pick first active branch + first customer
  const { data: branches, error: e1 } = await supabase.from("branches").select("id,name").limit(1);
  if (e1 || !branches?.[0]) throw new Error(`branch lookup failed: ${e1?.message ?? "no branches"}`);
  const { data: customers, error: e2 } = await supabase.from("customers").select("id,company").limit(1);
  if (e2 || !customers?.[0]) throw new Error(`customer lookup failed: ${e2?.message ?? "no customers"}`);
  const branchId = branches[0].id;
  const customerId = customers[0].id;

  console.log(`Using branch_id=${branchId} customer_id=${customerId}`);
  showExpectedSalesTypes();

  // Guard: skip if demo batch already present
  const { data: existing } = await supabase
    .from("invoices")
    .select("id,sales_type")
    .eq("compliance_json->>seed_batch", "p1-demo-001");
  if (existing && existing.length >= 7) {
    console.log("Demo batch p1-demo-001 already present — skipping insert.");
    console.table(existing);
    return;
  }

  const now = new Date().toISOString().slice(0, 10);

  // 7 demo invoices — one per SalesType (minimal amounts, status=draft)
  const demos: Array<Record<string, unknown>> = [
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "local_itemwise" as SalesType,
      is_tax_inclusive: false,
      supply_class: null,
      lut_no: null,
      transport_details: demoTransport("0001"),
      einvoice_status: "pending",
      eway_status: "not_required",
      compliance_json: { seed_batch: "p1-demo-001", note: "Local ItemWise — default single-rate" },
      subtotal: 10000,
      taxable_value: 10000,
      cgst: 900,
      sgst: 900,
      igst: 0,
      cess: 0,
      total: 11800,
      notes: "P1 demo: local_itemwise",
    },
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "local_multirate" as SalesType,
      is_tax_inclusive: false,
      supply_class: null,
      lut_no: null,
      transport_details: demoTransport("0002"),
      einvoice_status: "pending",
      eway_status: "pending",
      compliance_json: { seed_batch: "p1-demo-001", note: "Local MultiRate — ≥2 GST rates" },
      subtotal: 20000,
      taxable_value: 20000,
      cgst: 1800,
      sgst: 1800,
      igst: 0,
      cess: 0,
      total: 23600,
      notes: "P1 demo: local_multirate",
    },
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "local_multirate_cons" as SalesType,
      is_tax_inclusive: false,
      supply_class: null,
      lut_no: null,
      transport_details: demoTransport("0003"),
      einvoice_status: "pending",
      eway_status: "pending",
      compliance_json: { seed_batch: "p1-demo-001", note: "Local MultiRate Cons — consumption GL" },
      subtotal: 15000,
      taxable_value: 15000,
      cgst: 1350,
      sgst: 1350,
      igst: 0,
      cess: 0,
      total: 17700,
      notes: "P1 demo: local_multirate_cons",
    },
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "local_nil_rated" as SalesType,
      is_tax_inclusive: false,
      supply_class: "nil",
      lut_no: null,
      transport_details: demoTransport("0004"),
      einvoice_status: "not_required",
      eway_status: "not_required",
      compliance_json: { seed_batch: "p1-demo-001", note: "Local Nil Rated — Table 8" },
      subtotal: 5000,
      taxable_value: 5000,
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
      total: 5000,
      notes: "P1 demo: local_nil_rated",
    },
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "local_tax_incl" as SalesType,
      is_tax_inclusive: true,
      supply_class: null,
      lut_no: null,
      transport_details: demoTransport("0005"),
      einvoice_status: "pending",
      eway_status: "not_required",
      compliance_json: { seed_batch: "p1-demo-001", note: "Local Tax Incl — MRP back-calc" },
      subtotal: 10000,
      taxable_value: 8474,
      cgst: 763,
      sgst: 763,
      igst: 0,
      cess: 0,
      total: 10000,
      notes: "P1 demo: local_tax_incl (inclusive)",
    },
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "sez_taxable" as SalesType,
      is_tax_inclusive: false,
      supply_class: null,
      lut_no: null,
      transport_details: demoTransport("0006"),
      einvoice_status: "pending",
      eway_status: "pending",
      compliance_json: { seed_batch: "p1-demo-001", note: "SEZ Taxable — SEZWP IGST forced" },
      subtotal: 25000,
      taxable_value: 25000,
      cgst: 0,
      sgst: 0,
      igst: 4500,
      cess: 0,
      total: 29500,
      notes: "P1 demo: sez_taxable",
    },
    {
      branch_id: branchId,
      customer_id: customerId,
      invoice_date: now,
      status: "draft",
      sales_type: "sez_zero_rated" as SalesType,
      is_tax_inclusive: false,
      supply_class: "zero_rated",
      lut_no: "LUT/SEZ/2025-26/001",
      transport_details: demoTransport("0007"),
      einvoice_status: "pending",
      eway_status: "pending",
      compliance_json: { seed_batch: "p1-demo-001", note: "SEZ Zero Rated — LUT required" },
      subtotal: 30000,
      taxable_value: 30000,
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
      total: 30000,
      notes: "P1 demo: sez_zero_rated (LUT)",
    },
  ];

  for (const row of demos) {
    const { data, error } = await supabase.from("invoices").insert(row).select("id,invoice_no,sales_type,total").single();
    if (error) {
      console.error(`Insert failed for ${row["sales_type"]}:`, error.message);
    } else {
      console.log(`Inserted ${row["sales_type"]}:`, data);
      // Optionally insert one invoice_item per demo
      // const { error: eItem } = await supabase.from("invoice_items").insert({ invoice_id: data.id, sr_no: 1, description: `Demo item for ${row["sales_type"]}`, qty: 1, rate: row["total"] as number, gst_rate: 18, taxable_value: row["taxable_value"] as number, cgst: row["cgst"] as number, sgst: row["sgst"] as number, igst: row["igst"] as number, line_total: row["total"] as number });
      // if (eItem) console.warn("item insert skipped:", eItem.message);
    }
  }

  console.log("Seed complete. Verify with: SELECT sales_type, count(*) FROM invoices WHERE compliance_json->>'seed_batch'='p1-demo-001' GROUP BY sales_type;");
}

// Only run when executed directly, not when imported
if (import.meta.url === `file://${process.argv[1]}`) {
  // Uncomment to enable direct run:  seedInvoicingDemo().catch(console.error);
  console.log("This file is a MANUAL helper — not auto-run.");
  console.log("To seed: import { seedInvoicingDemo } from './scripts/seed_invoicing_demo.ts' and call seedInvoicingDemo(),");
  console.log("or uncomment the line below and run: npx tsx scripts/seed_invoicing_demo.ts");
  showExpectedSalesTypes();
  // seedInvoicingDemo().catch((e) => { console.error(e); process.exit(1); });
}
