/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaiseTicketRouteImport } from './routes/raise-ticket'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRecordsRouteImport } from './routes/_app/records'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppMastersRouteImport } from './routes/_app/masters'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppAmcRouteImport } from './routes/_app/amc'
import { Route as AppTicketsIndexRouteImport } from './routes/_app/tickets.index'
import { Route as AppCrmIndexRouteImport } from './routes/_app/crm.index'
import { Route as AppAmcIndexRouteImport } from './routes/_app/amc.index'
import { Route as AppTicketsTemplatesRouteImport } from './routes/_app/tickets.templates'
import { Route as AppTicketsNewRouteImport } from './routes/_app/tickets.new'
import { Route as AppTicketsDashboardRouteImport } from './routes/_app/tickets.dashboard'
import { Route as AppTicketsIdRouteImport } from './routes/_app/tickets.$id'
import { Route as AppMastersProductsRouteImport } from './routes/_app/masters.products'
import { Route as AppMastersCustomersRouteImport } from './routes/_app/masters.customers'
import { Route as AppGatepassIdRouteImport } from './routes/_app/gatepass.$id'
import { Route as AppCrmSettingsRouteImport } from './routes/_app/crm.settings'
import { Route as AppCrmQuotationsRouteImport } from './routes/_app/crm.quotations'
import { Route as AppCrmLeadsRouteImport } from './routes/_app/crm.leads'
import { Route as AppCrmIncentivesRouteImport } from './routes/_app/crm.incentives'
import { Route as AppCrmCustomersRouteImport } from './routes/_app/crm.customers'
import { Route as AppAmcSettingsRouteImport } from './routes/_app/amc.settings'
import { Route as AppAmcPmRouteImport } from './routes/_app/amc.pm'
import { Route as AppAmcNewRouteImport } from './routes/_app/amc.new'
import { Route as AppAmcIdRouteImport } from './routes/_app/amc.$id'
import { Route as AppCrmQuotationsIdRouteImport } from './routes/_app/crm.quotations.$id'
import { Route as AppCrmLeadsIdRouteImport } from './routes/_app/crm.leads.$id'

const RaiseTicketRoute = RaiseTicketRouteImport.update({
  id: '/raise-ticket',
  path: '/raise-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppAmcRoute = AppAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppAmcIndexRoute = AppAmcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppTicketsTemplatesRoute = AppTicketsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsNewRoute = AppTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsDashboardRoute = AppTicketsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsIdRoute = AppTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppMastersProductsRoute = AppMastersProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersCustomersRoute = AppMastersCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppGatepassIdRoute = AppGatepassIdRouteImport.update({
  id: '/gatepass/$id',
  path: '/gatepass/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmSettingsRoute = AppCrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmQuotationsRoute = AppCrmQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmIncentivesRoute = AppCrmIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppAmcSettingsRoute = AppAmcSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcPmRoute = AppAmcPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcNewRoute = AppAmcNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcIdRoute = AppAmcIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppCrmQuotationsIdRoute = AppCrmQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmQuotationsRoute,
} as any)
const AppCrmLeadsIdRoute = AppCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/raise-ticket': typeof RaiseTicketRoute
  '/amc': typeof AppAmcRouteWithChildren
  '/crm': typeof AppCrmRouteWithChildren
  '/import': typeof AppImportRoute
  '/masters': typeof AppMastersRouteWithChildren
  '/new': typeof AppNewRoute
  '/products': typeof AppProductsRoute
  '/records': typeof AppRecordsRoute
  '/reports': typeof AppReportsRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/amc/$id': typeof AppAmcIdRoute
  '/amc/new': typeof AppAmcNewRoute
  '/amc/pm': typeof AppAmcPmRoute
  '/amc/settings': typeof AppAmcSettingsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/incentives': typeof AppCrmIncentivesRoute
  '/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/crm/settings': typeof AppCrmSettingsRoute
  '/gatepass/$id': typeof AppGatepassIdRoute
  '/masters/customers': typeof AppMastersCustomersRoute
  '/masters/products': typeof AppMastersProductsRoute
  '/tickets/$id': typeof AppTicketsIdRoute
  '/tickets/dashboard': typeof AppTicketsDashboardRoute
  '/tickets/new': typeof AppTicketsNewRoute
  '/tickets/templates': typeof AppTicketsTemplatesRoute
  '/amc/': typeof AppAmcIndexRoute
  '/crm/': typeof AppCrmIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/raise-ticket': typeof RaiseTicketRoute
  '/import': typeof AppImportRoute
  '/masters': typeof AppMastersRouteWithChildren
  '/new': typeof AppNewRoute
  '/products': typeof AppProductsRoute
  '/records': typeof AppRecordsRoute
  '/reports': typeof AppReportsRoute
  '/amc/$id': typeof AppAmcIdRoute
  '/amc/new': typeof AppAmcNewRoute
  '/amc/pm': typeof AppAmcPmRoute
  '/amc/settings': typeof AppAmcSettingsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/incentives': typeof AppCrmIncentivesRoute
  '/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/crm/settings': typeof AppCrmSettingsRoute
  '/gatepass/$id': typeof AppGatepassIdRoute
  '/masters/customers': typeof AppMastersCustomersRoute
  '/masters/products': typeof AppMastersProductsRoute
  '/tickets/$id': typeof AppTicketsIdRoute
  '/tickets/dashboard': typeof AppTicketsDashboardRoute
  '/tickets/new': typeof AppTicketsNewRoute
  '/tickets/templates': typeof AppTicketsTemplatesRoute
  '/amc': typeof AppAmcIndexRoute
  '/crm': typeof AppCrmIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/raise-ticket': typeof RaiseTicketRoute
  '/_app/amc': typeof AppAmcRouteWithChildren
  '/_app/crm': typeof AppCrmRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/_app/masters': typeof AppMastersRouteWithChildren
  '/_app/new': typeof AppNewRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/tickets': typeof AppTicketsRouteWithChildren
  '/_app/amc/$id': typeof AppAmcIdRoute
  '/_app/amc/new': typeof AppAmcNewRoute
  '/_app/amc/pm': typeof AppAmcPmRoute
  '/_app/amc/settings': typeof AppAmcSettingsRoute
  '/_app/crm/customers': typeof AppCrmCustomersRoute
  '/_app/crm/incentives': typeof AppCrmIncentivesRoute
  '/_app/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/_app/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/_app/crm/settings': typeof AppCrmSettingsRoute
  '/_app/gatepass/$id': typeof AppGatepassIdRoute
  '/_app/masters/customers': typeof AppMastersCustomersRoute
  '/_app/masters/products': typeof AppMastersProductsRoute
  '/_app/tickets/$id': typeof AppTicketsIdRoute
  '/_app/tickets/dashboard': typeof AppTicketsDashboardRoute
  '/_app/tickets/new': typeof AppTicketsNewRoute
  '/_app/tickets/templates': typeof AppTicketsTemplatesRoute
  '/_app/amc/': typeof AppAmcIndexRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
  '/_app/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/_app/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/raise-ticket'
    | '/amc'
    | '/crm'
    | '/import'
    | '/masters'
    | '/new'
    | '/products'
    | '/records'
    | '/reports'
    | '/tickets'
    | '/amc/$id'
    | '/amc/new'
    | '/amc/pm'
    | '/amc/settings'
    | '/crm/customers'
    | '/crm/incentives'
    | '/crm/leads'
    | '/crm/quotations'
    | '/crm/settings'
    | '/gatepass/$id'
    | '/masters/customers'
    | '/masters/products'
    | '/tickets/$id'
    | '/tickets/dashboard'
    | '/tickets/new'
    | '/tickets/templates'
    | '/amc/'
    | '/crm/'
    | '/tickets/'
    | '/crm/leads/$id'
    | '/crm/quotations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/raise-ticket'
    | '/import'
    | '/masters'
    | '/new'
    | '/products'
    | '/records'
    | '/reports'
    | '/amc/$id'
    | '/amc/new'
    | '/amc/pm'
    | '/amc/settings'
    | '/crm/customers'
    | '/crm/incentives'
    | '/crm/leads'
    | '/crm/quotations'
    | '/crm/settings'
    | '/gatepass/$id'
    | '/masters/customers'
    | '/masters/products'
    | '/tickets/$id'
    | '/tickets/dashboard'
    | '/tickets/new'
    | '/tickets/templates'
    | '/amc'
    | '/crm'
    | '/tickets'
    | '/crm/leads/$id'
    | '/crm/quotations/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/raise-ticket'
    | '/_app/amc'
    | '/_app/crm'
    | '/_app/import'
    | '/_app/masters'
    | '/_app/new'
    | '/_app/products'
    | '/_app/records'
    | '/_app/reports'
    | '/_app/tickets'
    | '/_app/amc/$id'
    | '/_app/amc/new'
    | '/_app/amc/pm'
    | '/_app/amc/settings'
    | '/_app/crm/customers'
    | '/_app/crm/incentives'
    | '/_app/crm/leads'
    | '/_app/crm/quotations'
    | '/_app/crm/settings'
    | '/_app/gatepass/$id'
    | '/_app/masters/customers'
    | '/_app/masters/products'
    | '/_app/tickets/$id'
    | '/_app/tickets/dashboard'
    | '/_app/tickets/new'
    | '/_app/tickets/templates'
    | '/_app/amc/'
    | '/_app/crm/'
    | '/_app/tickets/'
    | '/_app/crm/leads/$id'
    | '/_app/crm/quotations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RaiseTicketRoute: typeof RaiseTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raise-ticket': {
      id: '/raise-ticket'
      path: '/raise-ticket'
      fullPath: '/raise-ticket'
      preLoaderRoute: typeof RaiseTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/amc': {
      id: '/_app/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AppAmcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/amc/': {
      id: '/_app/amc/'
      path: '/'
      fullPath: '/amc/'
      preLoaderRoute: typeof AppAmcIndexRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/tickets/templates': {
      id: '/_app/tickets/templates'
      path: '/templates'
      fullPath: '/tickets/templates'
      preLoaderRoute: typeof AppTicketsTemplatesRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/new': {
      id: '/_app/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AppTicketsNewRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/dashboard': {
      id: '/_app/tickets/dashboard'
      path: '/dashboard'
      fullPath: '/tickets/dashboard'
      preLoaderRoute: typeof AppTicketsDashboardRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/$id': {
      id: '/_app/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AppTicketsIdRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/masters/products': {
      id: '/_app/masters/products'
      path: '/products'
      fullPath: '/masters/products'
      preLoaderRoute: typeof AppMastersProductsRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/masters/customers': {
      id: '/_app/masters/customers'
      path: '/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof AppMastersCustomersRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/gatepass/$id': {
      id: '/_app/gatepass/$id'
      path: '/gatepass/$id'
      fullPath: '/gatepass/$id'
      preLoaderRoute: typeof AppGatepassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/settings': {
      id: '/_app/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AppCrmSettingsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/quotations': {
      id: '/_app/crm/quotations'
      path: '/quotations'
      fullPath: '/crm/quotations'
      preLoaderRoute: typeof AppCrmQuotationsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/leads': {
      id: '/_app/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/incentives': {
      id: '/_app/crm/incentives'
      path: '/incentives'
      fullPath: '/crm/incentives'
      preLoaderRoute: typeof AppCrmIncentivesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/customers': {
      id: '/_app/crm/customers'
      path: '/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/amc/settings': {
      id: '/_app/amc/settings'
      path: '/settings'
      fullPath: '/amc/settings'
      preLoaderRoute: typeof AppAmcSettingsRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/pm': {
      id: '/_app/amc/pm'
      path: '/pm'
      fullPath: '/amc/pm'
      preLoaderRoute: typeof AppAmcPmRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/new': {
      id: '/_app/amc/new'
      path: '/new'
      fullPath: '/amc/new'
      preLoaderRoute: typeof AppAmcNewRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/$id': {
      id: '/_app/amc/$id'
      path: '/$id'
      fullPath: '/amc/$id'
      preLoaderRoute: typeof AppAmcIdRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/crm/quotations/$id': {
      id: '/_app/crm/quotations/$id'
      path: '/$id'
      fullPath: '/crm/quotations/$id'
      preLoaderRoute: typeof AppCrmQuotationsIdRouteImport
      parentRoute: typeof AppCrmQuotationsRoute
    }
    '/_app/crm/leads/$id': {
      id: '/_app/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AppCrmLeadsIdRouteImport
      parentRoute: typeof AppCrmLeadsRoute
    }
  }
}

interface AppAmcRouteChildren {
  AppAmcIdRoute: typeof AppAmcIdRoute
  AppAmcNewRoute: typeof AppAmcNewRoute
  AppAmcPmRoute: typeof AppAmcPmRoute
  AppAmcSettingsRoute: typeof AppAmcSettingsRoute
  AppAmcIndexRoute: typeof AppAmcIndexRoute
}

const AppAmcRouteChildren: AppAmcRouteChildren = {
  AppAmcIdRoute: AppAmcIdRoute,
  AppAmcNewRoute: AppAmcNewRoute,
  AppAmcPmRoute: AppAmcPmRoute,
  AppAmcSettingsRoute: AppAmcSettingsRoute,
  AppAmcIndexRoute: AppAmcIndexRoute,
}

const AppAmcRouteWithChildren =
  AppAmcRoute._addFileChildren(AppAmcRouteChildren)

interface AppCrmLeadsRouteChildren {
  AppCrmLeadsIdRoute: typeof AppCrmLeadsIdRoute
}

const AppCrmLeadsRouteChildren: AppCrmLeadsRouteChildren = {
  AppCrmLeadsIdRoute: AppCrmLeadsIdRoute,
}

const AppCrmLeadsRouteWithChildren = AppCrmLeadsRoute._addFileChildren(
  AppCrmLeadsRouteChildren,
)

interface AppCrmQuotationsRouteChildren {
  AppCrmQuotationsIdRoute: typeof AppCrmQuotationsIdRoute
}

const AppCrmQuotationsRouteChildren: AppCrmQuotationsRouteChildren = {
  AppCrmQuotationsIdRoute: AppCrmQuotationsIdRoute,
}

const AppCrmQuotationsRouteWithChildren =
  AppCrmQuotationsRoute._addFileChildren(AppCrmQuotationsRouteChildren)

interface AppCrmRouteChildren {
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmIncentivesRoute: typeof AppCrmIncentivesRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRouteWithChildren
  AppCrmQuotationsRoute: typeof AppCrmQuotationsRouteWithChildren
  AppCrmSettingsRoute: typeof AppCrmSettingsRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmIncentivesRoute: AppCrmIncentivesRoute,
  AppCrmLeadsRoute: AppCrmLeadsRouteWithChildren,
  AppCrmQuotationsRoute: AppCrmQuotationsRouteWithChildren,
  AppCrmSettingsRoute: AppCrmSettingsRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppMastersRouteChildren {
  AppMastersCustomersRoute: typeof AppMastersCustomersRoute
  AppMastersProductsRoute: typeof AppMastersProductsRoute
}

const AppMastersRouteChildren: AppMastersRouteChildren = {
  AppMastersCustomersRoute: AppMastersCustomersRoute,
  AppMastersProductsRoute: AppMastersProductsRoute,
}

const AppMastersRouteWithChildren = AppMastersRoute._addFileChildren(
  AppMastersRouteChildren,
)

interface AppTicketsRouteChildren {
  AppTicketsIdRoute: typeof AppTicketsIdRoute
  AppTicketsDashboardRoute: typeof AppTicketsDashboardRoute
  AppTicketsNewRoute: typeof AppTicketsNewRoute
  AppTicketsTemplatesRoute: typeof AppTicketsTemplatesRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsIdRoute: AppTicketsIdRoute,
  AppTicketsDashboardRoute: AppTicketsDashboardRoute,
  AppTicketsNewRoute: AppTicketsNewRoute,
  AppTicketsTemplatesRoute: AppTicketsTemplatesRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppRouteChildren {
  AppAmcRoute: typeof AppAmcRouteWithChildren
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppMastersRoute: typeof AppMastersRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppProductsRoute: typeof AppProductsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppGatepassIdRoute: typeof AppGatepassIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmcRoute: AppAmcRouteWithChildren,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppMastersRoute: AppMastersRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppProductsRoute: AppProductsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppGatepassIdRoute: AppGatepassIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RaiseTicketRoute: RaiseTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
