/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecordsRouteImport } from './routes/_app/records'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppAmcRouteImport } from './routes/_app/amc'
import { Route as AppCrmIndexRouteImport } from './routes/_app/crm.index'
import { Route as AppAmcIndexRouteImport } from './routes/_app/amc.index'
import { Route as AppGatepassIdRouteImport } from './routes/_app/gatepass.$id'
import { Route as AppCrmQuotationsRouteImport } from './routes/_app/crm.quotations'
import { Route as AppCrmLeadsRouteImport } from './routes/_app/crm.leads'
import { Route as AppCrmCustomersRouteImport } from './routes/_app/crm.customers'
import { Route as AppAmcSettingsRouteImport } from './routes/_app/amc.settings'
import { Route as AppAmcPmRouteImport } from './routes/_app/amc.pm'
import { Route as AppAmcNewRouteImport } from './routes/_app/amc.new'
import { Route as AppAmcIdRouteImport } from './routes/_app/amc.$id'
import { Route as AppCrmQuotationsIdRouteImport } from './routes/_app/crm.quotations.$id'
import { Route as AppCrmLeadsIdRouteImport } from './routes/_app/crm.leads.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppAmcRoute = AppAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppAmcIndexRoute = AppAmcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppGatepassIdRoute = AppGatepassIdRouteImport.update({
  id: '/gatepass/$id',
  path: '/gatepass/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmQuotationsRoute = AppCrmQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppAmcSettingsRoute = AppAmcSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcPmRoute = AppAmcPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcNewRoute = AppAmcNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcIdRoute = AppAmcIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppCrmQuotationsIdRoute = AppCrmQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmQuotationsRoute,
} as any)
const AppCrmLeadsIdRoute = AppCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/amc': typeof AppAmcRouteWithChildren
  '/crm': typeof AppCrmRouteWithChildren
  '/new': typeof AppNewRoute
  '/products': typeof AppProductsRoute
  '/records': typeof AppRecordsRoute
  '/amc/$id': typeof AppAmcIdRoute
  '/amc/new': typeof AppAmcNewRoute
  '/amc/pm': typeof AppAmcPmRoute
  '/amc/settings': typeof AppAmcSettingsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/gatepass/$id': typeof AppGatepassIdRoute
  '/amc/': typeof AppAmcIndexRoute
  '/crm/': typeof AppCrmIndexRoute
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof AppNewRoute
  '/products': typeof AppProductsRoute
  '/records': typeof AppRecordsRoute
  '/amc/$id': typeof AppAmcIdRoute
  '/amc/new': typeof AppAmcNewRoute
  '/amc/pm': typeof AppAmcPmRoute
  '/amc/settings': typeof AppAmcSettingsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/gatepass/$id': typeof AppGatepassIdRoute
  '/amc': typeof AppAmcIndexRoute
  '/crm': typeof AppCrmIndexRoute
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/amc': typeof AppAmcRouteWithChildren
  '/_app/crm': typeof AppCrmRouteWithChildren
  '/_app/new': typeof AppNewRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/amc/$id': typeof AppAmcIdRoute
  '/_app/amc/new': typeof AppAmcNewRoute
  '/_app/amc/pm': typeof AppAmcPmRoute
  '/_app/amc/settings': typeof AppAmcSettingsRoute
  '/_app/crm/customers': typeof AppCrmCustomersRoute
  '/_app/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/_app/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/_app/gatepass/$id': typeof AppGatepassIdRoute
  '/_app/amc/': typeof AppAmcIndexRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/_app/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/amc'
    | '/crm'
    | '/new'
    | '/products'
    | '/records'
    | '/amc/$id'
    | '/amc/new'
    | '/amc/pm'
    | '/amc/settings'
    | '/crm/customers'
    | '/crm/leads'
    | '/crm/quotations'
    | '/gatepass/$id'
    | '/amc/'
    | '/crm/'
    | '/crm/leads/$id'
    | '/crm/quotations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/new'
    | '/products'
    | '/records'
    | '/amc/$id'
    | '/amc/new'
    | '/amc/pm'
    | '/amc/settings'
    | '/crm/customers'
    | '/crm/leads'
    | '/crm/quotations'
    | '/gatepass/$id'
    | '/amc'
    | '/crm'
    | '/crm/leads/$id'
    | '/crm/quotations/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/amc'
    | '/_app/crm'
    | '/_app/new'
    | '/_app/products'
    | '/_app/records'
    | '/_app/amc/$id'
    | '/_app/amc/new'
    | '/_app/amc/pm'
    | '/_app/amc/settings'
    | '/_app/crm/customers'
    | '/_app/crm/leads'
    | '/_app/crm/quotations'
    | '/_app/gatepass/$id'
    | '/_app/amc/'
    | '/_app/crm/'
    | '/_app/crm/leads/$id'
    | '/_app/crm/quotations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/amc': {
      id: '/_app/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AppAmcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/amc/': {
      id: '/_app/amc/'
      path: '/'
      fullPath: '/amc/'
      preLoaderRoute: typeof AppAmcIndexRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/gatepass/$id': {
      id: '/_app/gatepass/$id'
      path: '/gatepass/$id'
      fullPath: '/gatepass/$id'
      preLoaderRoute: typeof AppGatepassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/quotations': {
      id: '/_app/crm/quotations'
      path: '/quotations'
      fullPath: '/crm/quotations'
      preLoaderRoute: typeof AppCrmQuotationsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/leads': {
      id: '/_app/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/customers': {
      id: '/_app/crm/customers'
      path: '/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/amc/settings': {
      id: '/_app/amc/settings'
      path: '/settings'
      fullPath: '/amc/settings'
      preLoaderRoute: typeof AppAmcSettingsRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/pm': {
      id: '/_app/amc/pm'
      path: '/pm'
      fullPath: '/amc/pm'
      preLoaderRoute: typeof AppAmcPmRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/new': {
      id: '/_app/amc/new'
      path: '/new'
      fullPath: '/amc/new'
      preLoaderRoute: typeof AppAmcNewRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/$id': {
      id: '/_app/amc/$id'
      path: '/$id'
      fullPath: '/amc/$id'
      preLoaderRoute: typeof AppAmcIdRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/crm/quotations/$id': {
      id: '/_app/crm/quotations/$id'
      path: '/$id'
      fullPath: '/crm/quotations/$id'
      preLoaderRoute: typeof AppCrmQuotationsIdRouteImport
      parentRoute: typeof AppCrmQuotationsRoute
    }
    '/_app/crm/leads/$id': {
      id: '/_app/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AppCrmLeadsIdRouteImport
      parentRoute: typeof AppCrmLeadsRoute
    }
  }
}

interface AppAmcRouteChildren {
  AppAmcIdRoute: typeof AppAmcIdRoute
  AppAmcNewRoute: typeof AppAmcNewRoute
  AppAmcPmRoute: typeof AppAmcPmRoute
  AppAmcSettingsRoute: typeof AppAmcSettingsRoute
  AppAmcIndexRoute: typeof AppAmcIndexRoute
}

const AppAmcRouteChildren: AppAmcRouteChildren = {
  AppAmcIdRoute: AppAmcIdRoute,
  AppAmcNewRoute: AppAmcNewRoute,
  AppAmcPmRoute: AppAmcPmRoute,
  AppAmcSettingsRoute: AppAmcSettingsRoute,
  AppAmcIndexRoute: AppAmcIndexRoute,
}

const AppAmcRouteWithChildren =
  AppAmcRoute._addFileChildren(AppAmcRouteChildren)

interface AppCrmLeadsRouteChildren {
  AppCrmLeadsIdRoute: typeof AppCrmLeadsIdRoute
}

const AppCrmLeadsRouteChildren: AppCrmLeadsRouteChildren = {
  AppCrmLeadsIdRoute: AppCrmLeadsIdRoute,
}

const AppCrmLeadsRouteWithChildren = AppCrmLeadsRoute._addFileChildren(
  AppCrmLeadsRouteChildren,
)

interface AppCrmQuotationsRouteChildren {
  AppCrmQuotationsIdRoute: typeof AppCrmQuotationsIdRoute
}

const AppCrmQuotationsRouteChildren: AppCrmQuotationsRouteChildren = {
  AppCrmQuotationsIdRoute: AppCrmQuotationsIdRoute,
}

const AppCrmQuotationsRouteWithChildren =
  AppCrmQuotationsRoute._addFileChildren(AppCrmQuotationsRouteChildren)

interface AppCrmRouteChildren {
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRouteWithChildren
  AppCrmQuotationsRoute: typeof AppCrmQuotationsRouteWithChildren
  AppCrmIndexRoute: typeof AppCrmIndexRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmLeadsRoute: AppCrmLeadsRouteWithChildren,
  AppCrmQuotationsRoute: AppCrmQuotationsRouteWithChildren,
  AppCrmIndexRoute: AppCrmIndexRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppRouteChildren {
  AppAmcRoute: typeof AppAmcRouteWithChildren
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppProductsRoute: typeof AppProductsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppGatepassIdRoute: typeof AppGatepassIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmcRoute: AppAmcRouteWithChildren,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppProductsRoute: AppProductsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppGatepassIdRoute: AppGatepassIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
