/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaiseTicketRouteImport } from './routes/raise-ticket'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRecordsRouteImport } from './routes/_app/records'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPoRouteImport } from './routes/_app/po'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppMastersRouteImport } from './routes/_app/masters'
import { Route as AppIndentRouteImport } from './routes/_app/indent'
import { Route as AppImsRouteImport } from './routes/_app/ims'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppGrnRouteImport } from './routes/_app/grn'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppChallanRouteImport } from './routes/_app/challan'
import { Route as AppArchiveRouteImport } from './routes/_app/archive'
import { Route as AppAmcRouteImport } from './routes/_app/amc'
import { Route as AppTicketsIndexRouteImport } from './routes/_app/tickets.index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales.index'
import { Route as AppPoIndexRouteImport } from './routes/_app/po.index'
import { Route as AppIndentIndexRouteImport } from './routes/_app/indent.index'
import { Route as AppImsIndexRouteImport } from './routes/_app/ims.index'
import { Route as AppGrnIndexRouteImport } from './routes/_app/grn.index'
import { Route as AppCrmIndexRouteImport } from './routes/_app/crm.index'
import { Route as AppChallanIndexRouteImport } from './routes/_app/challan.index'
import { Route as AppAmcIndexRouteImport } from './routes/_app/amc.index'
import { Route as AppTicketsTemplatesRouteImport } from './routes/_app/tickets.templates'
import { Route as AppTicketsSettingsRouteImport } from './routes/_app/tickets.settings'
import { Route as AppTicketsNewRouteImport } from './routes/_app/tickets.new'
import { Route as AppTicketsDashboardRouteImport } from './routes/_app/tickets.dashboard'
import { Route as AppTicketsIdRouteImport } from './routes/_app/tickets.$id'
import { Route as AppSalesSettingsRouteImport } from './routes/_app/sales.settings'
import { Route as AppSalesQuotationsRouteImport } from './routes/_app/sales.quotations'
import { Route as AppPoSettingsRouteImport } from './routes/_app/po.settings'
import { Route as AppPoNewRouteImport } from './routes/_app/po.new'
import { Route as AppPoIdRouteImport } from './routes/_app/po.$id'
import { Route as AppMastersProductsRouteImport } from './routes/_app/masters.products'
import { Route as AppMastersCustomersRouteImport } from './routes/_app/masters.customers'
import { Route as AppIndentNewRouteImport } from './routes/_app/indent.new'
import { Route as AppIndentIdRouteImport } from './routes/_app/indent.$id'
import { Route as AppImsTransfersRouteImport } from './routes/_app/ims.transfers'
import { Route as AppImsTransactionsRouteImport } from './routes/_app/ims.transactions'
import { Route as AppImsStockRouteImport } from './routes/_app/ims.stock'
import { Route as AppImsReservationsRouteImport } from './routes/_app/ims.reservations'
import { Route as AppImsReportsRouteImport } from './routes/_app/ims.reports'
import { Route as AppImsOemReturnsRouteImport } from './routes/_app/ims.oem-returns'
import { Route as AppImsIndentHistoryRouteImport } from './routes/_app/ims.indent-history'
import { Route as AppImsAuditRouteImport } from './routes/_app/ims.audit'
import { Route as AppGrnOemRouteImport } from './routes/_app/grn.oem'
import { Route as AppGrnGeneralRouteImport } from './routes/_app/grn.general'
import { Route as AppGrnCustomerRouteImport } from './routes/_app/grn.customer'
import { Route as AppGrnIdRouteImport } from './routes/_app/grn.$id'
import { Route as AppGatepassIdRouteImport } from './routes/_app/gatepass.$id'
import { Route as AppCrmSettingsRouteImport } from './routes/_app/crm.settings'
import { Route as AppCrmQuotationsRouteImport } from './routes/_app/crm.quotations'
import { Route as AppCrmLeadsRouteImport } from './routes/_app/crm.leads'
import { Route as AppCrmIncentivesRouteImport } from './routes/_app/crm.incentives'
import { Route as AppCrmCustomersRouteImport } from './routes/_app/crm.customers'
import { Route as AppCrmBundlesRouteImport } from './routes/_app/crm.bundles'
import { Route as AppChallanOemRouteImport } from './routes/_app/challan.oem'
import { Route as AppChallanCustomerRouteImport } from './routes/_app/challan.customer'
import { Route as AppChallanIdRouteImport } from './routes/_app/challan.$id'
import { Route as AppAmcSettingsRouteImport } from './routes/_app/amc.settings'
import { Route as AppAmcPmRouteImport } from './routes/_app/amc.pm'
import { Route as AppAmcOemRouteImport } from './routes/_app/amc.oem'
import { Route as AppAmcNewRouteImport } from './routes/_app/amc.new'
import { Route as AppAmcIdRouteImport } from './routes/_app/amc.$id'
import { Route as AppSalesPaymentsIndexRouteImport } from './routes/_app/sales.payments.index'
import { Route as AppSalesInvoicesIndexRouteImport } from './routes/_app/sales.invoices.index'
import { Route as AppSalesEwayIndexRouteImport } from './routes/_app/sales.eway.index'
import { Route as AppImsTransfersIndexRouteImport } from './routes/_app/ims.transfers.index'
import { Route as AppGrnOemIndexRouteImport } from './routes/_app/grn.oem.index'
import { Route as AppGrnGeneralIndexRouteImport } from './routes/_app/grn.general.index'
import { Route as AppGrnCustomerIndexRouteImport } from './routes/_app/grn.customer.index'
import { Route as AppChallanOemIndexRouteImport } from './routes/_app/challan.oem.index'
import { Route as AppChallanCustomerIndexRouteImport } from './routes/_app/challan.customer.index'
import { Route as AppSalesPaymentsNewRouteImport } from './routes/_app/sales.payments.new'
import { Route as AppSalesInvoicesNewRouteImport } from './routes/_app/sales.invoices.new'
import { Route as AppSalesInvoicesIdRouteImport } from './routes/_app/sales.invoices.$id'
import { Route as AppImsTransfersNewRouteImport } from './routes/_app/ims.transfers.new'
import { Route as AppImsTransfersIdRouteImport } from './routes/_app/ims.transfers.$id'
import { Route as AppGrnOemNewRouteImport } from './routes/_app/grn.oem.new'
import { Route as AppGrnGeneralNewRouteImport } from './routes/_app/grn.general.new'
import { Route as AppGrnCustomerNewRouteImport } from './routes/_app/grn.customer.new'
import { Route as AppCrmQuotationsIdRouteImport } from './routes/_app/crm.quotations.$id'
import { Route as AppCrmLeadsIdRouteImport } from './routes/_app/crm.leads.$id'
import { Route as AppChallanOemNewRouteImport } from './routes/_app/challan.oem.new'
import { Route as AppChallanCustomerNewRouteImport } from './routes/_app/challan.customer.new'

const RaiseTicketRoute = RaiseTicketRouteImport.update({
  id: '/raise-ticket',
  path: '/raise-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPoRoute = AppPoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppIndentRoute = AppIndentRouteImport.update({
  id: '/indent',
  path: '/indent',
  getParentRoute: () => AppRoute,
} as any)
const AppImsRoute = AppImsRouteImport.update({
  id: '/ims',
  path: '/ims',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppGrnRoute = AppGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppChallanRoute = AppChallanRouteImport.update({
  id: '/challan',
  path: '/challan',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppAmcRoute = AppAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPoIndexRoute = AppPoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPoRoute,
} as any)
const AppIndentIndexRoute = AppIndentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIndentRoute,
} as any)
const AppImsIndexRoute = AppImsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppImsRoute,
} as any)
const AppGrnIndexRoute = AppGrnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrnRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppChallanIndexRoute = AppChallanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChallanRoute,
} as any)
const AppAmcIndexRoute = AppAmcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppTicketsTemplatesRoute = AppTicketsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsSettingsRoute = AppTicketsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsNewRoute = AppTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsDashboardRoute = AppTicketsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsIdRoute = AppTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppSalesSettingsRoute = AppSalesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesQuotationsRoute = AppSalesQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPoSettingsRoute = AppPoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPoRoute,
} as any)
const AppPoNewRoute = AppPoNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPoRoute,
} as any)
const AppPoIdRoute = AppPoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPoRoute,
} as any)
const AppMastersProductsRoute = AppMastersProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersCustomersRoute = AppMastersCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppIndentNewRoute = AppIndentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppIndentRoute,
} as any)
const AppIndentIdRoute = AppIndentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIndentRoute,
} as any)
const AppImsTransfersRoute = AppImsTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsTransactionsRoute = AppImsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsStockRoute = AppImsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsReservationsRoute = AppImsReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsReportsRoute = AppImsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsOemReturnsRoute = AppImsOemReturnsRouteImport.update({
  id: '/oem-returns',
  path: '/oem-returns',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsIndentHistoryRoute = AppImsIndentHistoryRouteImport.update({
  id: '/indent-history',
  path: '/indent-history',
  getParentRoute: () => AppImsRoute,
} as any)
const AppImsAuditRoute = AppImsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppImsRoute,
} as any)
const AppGrnOemRoute = AppGrnOemRouteImport.update({
  id: '/oem',
  path: '/oem',
  getParentRoute: () => AppGrnRoute,
} as any)
const AppGrnGeneralRoute = AppGrnGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppGrnRoute,
} as any)
const AppGrnCustomerRoute = AppGrnCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AppGrnRoute,
} as any)
const AppGrnIdRoute = AppGrnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGrnRoute,
} as any)
const AppGatepassIdRoute = AppGatepassIdRouteImport.update({
  id: '/gatepass/$id',
  path: '/gatepass/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmSettingsRoute = AppCrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmQuotationsRoute = AppCrmQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmIncentivesRoute = AppCrmIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmBundlesRoute = AppCrmBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppChallanOemRoute = AppChallanOemRouteImport.update({
  id: '/oem',
  path: '/oem',
  getParentRoute: () => AppChallanRoute,
} as any)
const AppChallanCustomerRoute = AppChallanCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AppChallanRoute,
} as any)
const AppChallanIdRoute = AppChallanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChallanRoute,
} as any)
const AppAmcSettingsRoute = AppAmcSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcPmRoute = AppAmcPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcOemRoute = AppAmcOemRouteImport.update({
  id: '/oem',
  path: '/oem',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcNewRoute = AppAmcNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppAmcIdRoute = AppAmcIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAmcRoute,
} as any)
const AppSalesPaymentsIndexRoute = AppSalesPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesInvoicesIndexRoute = AppSalesInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesEwayIndexRoute = AppSalesEwayIndexRouteImport.update({
  id: '/eway/',
  path: '/eway/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppImsTransfersIndexRoute = AppImsTransfersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppImsTransfersRoute,
} as any)
const AppGrnOemIndexRoute = AppGrnOemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrnOemRoute,
} as any)
const AppGrnGeneralIndexRoute = AppGrnGeneralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrnGeneralRoute,
} as any)
const AppGrnCustomerIndexRoute = AppGrnCustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrnCustomerRoute,
} as any)
const AppChallanOemIndexRoute = AppChallanOemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChallanOemRoute,
} as any)
const AppChallanCustomerIndexRoute = AppChallanCustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChallanCustomerRoute,
} as any)
const AppSalesPaymentsNewRoute = AppSalesPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesInvoicesNewRoute = AppSalesInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesInvoicesIdRoute = AppSalesInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppImsTransfersNewRoute = AppImsTransfersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppImsTransfersRoute,
} as any)
const AppImsTransfersIdRoute = AppImsTransfersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppImsTransfersRoute,
} as any)
const AppGrnOemNewRoute = AppGrnOemNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppGrnOemRoute,
} as any)
const AppGrnGeneralNewRoute = AppGrnGeneralNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppGrnGeneralRoute,
} as any)
const AppGrnCustomerNewRoute = AppGrnCustomerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppGrnCustomerRoute,
} as any)
const AppCrmQuotationsIdRoute = AppCrmQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmQuotationsRoute,
} as any)
const AppCrmLeadsIdRoute = AppCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmLeadsRoute,
} as any)
const AppChallanOemNewRoute = AppChallanOemNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppChallanOemRoute,
} as any)
const AppChallanCustomerNewRoute = AppChallanCustomerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppChallanCustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/raise-ticket': typeof RaiseTicketRoute
  '/amc': typeof AppAmcRouteWithChildren
  '/archive': typeof AppArchiveRoute
  '/challan': typeof AppChallanRouteWithChildren
  '/crm': typeof AppCrmRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/grn': typeof AppGrnRouteWithChildren
  '/import': typeof AppImportRoute
  '/ims': typeof AppImsRouteWithChildren
  '/indent': typeof AppIndentRouteWithChildren
  '/masters': typeof AppMastersRouteWithChildren
  '/new': typeof AppNewRoute
  '/po': typeof AppPoRouteWithChildren
  '/products': typeof AppProductsRoute
  '/records': typeof AppRecordsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRouteWithChildren
  '/tickets': typeof AppTicketsRouteWithChildren
  '/amc/$id': typeof AppAmcIdRoute
  '/amc/new': typeof AppAmcNewRoute
  '/amc/oem': typeof AppAmcOemRoute
  '/amc/pm': typeof AppAmcPmRoute
  '/amc/settings': typeof AppAmcSettingsRoute
  '/challan/$id': typeof AppChallanIdRoute
  '/challan/customer': typeof AppChallanCustomerRouteWithChildren
  '/challan/oem': typeof AppChallanOemRouteWithChildren
  '/crm/bundles': typeof AppCrmBundlesRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/incentives': typeof AppCrmIncentivesRoute
  '/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/crm/settings': typeof AppCrmSettingsRoute
  '/gatepass/$id': typeof AppGatepassIdRoute
  '/grn/$id': typeof AppGrnIdRoute
  '/grn/customer': typeof AppGrnCustomerRouteWithChildren
  '/grn/general': typeof AppGrnGeneralRouteWithChildren
  '/grn/oem': typeof AppGrnOemRouteWithChildren
  '/ims/audit': typeof AppImsAuditRoute
  '/ims/indent-history': typeof AppImsIndentHistoryRoute
  '/ims/oem-returns': typeof AppImsOemReturnsRoute
  '/ims/reports': typeof AppImsReportsRoute
  '/ims/reservations': typeof AppImsReservationsRoute
  '/ims/stock': typeof AppImsStockRoute
  '/ims/transactions': typeof AppImsTransactionsRoute
  '/ims/transfers': typeof AppImsTransfersRouteWithChildren
  '/indent/$id': typeof AppIndentIdRoute
  '/indent/new': typeof AppIndentNewRoute
  '/masters/customers': typeof AppMastersCustomersRoute
  '/masters/products': typeof AppMastersProductsRoute
  '/po/$id': typeof AppPoIdRoute
  '/po/new': typeof AppPoNewRoute
  '/po/settings': typeof AppPoSettingsRoute
  '/sales/quotations': typeof AppSalesQuotationsRoute
  '/sales/settings': typeof AppSalesSettingsRoute
  '/tickets/$id': typeof AppTicketsIdRoute
  '/tickets/dashboard': typeof AppTicketsDashboardRoute
  '/tickets/new': typeof AppTicketsNewRoute
  '/tickets/settings': typeof AppTicketsSettingsRoute
  '/tickets/templates': typeof AppTicketsTemplatesRoute
  '/amc/': typeof AppAmcIndexRoute
  '/challan/': typeof AppChallanIndexRoute
  '/crm/': typeof AppCrmIndexRoute
  '/grn/': typeof AppGrnIndexRoute
  '/ims/': typeof AppImsIndexRoute
  '/indent/': typeof AppIndentIndexRoute
  '/po/': typeof AppPoIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
  '/challan/customer/new': typeof AppChallanCustomerNewRoute
  '/challan/oem/new': typeof AppChallanOemNewRoute
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
  '/grn/customer/new': typeof AppGrnCustomerNewRoute
  '/grn/general/new': typeof AppGrnGeneralNewRoute
  '/grn/oem/new': typeof AppGrnOemNewRoute
  '/ims/transfers/$id': typeof AppImsTransfersIdRoute
  '/ims/transfers/new': typeof AppImsTransfersNewRoute
  '/sales/invoices/$id': typeof AppSalesInvoicesIdRoute
  '/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/sales/payments/new': typeof AppSalesPaymentsNewRoute
  '/challan/customer/': typeof AppChallanCustomerIndexRoute
  '/challan/oem/': typeof AppChallanOemIndexRoute
  '/grn/customer/': typeof AppGrnCustomerIndexRoute
  '/grn/general/': typeof AppGrnGeneralIndexRoute
  '/grn/oem/': typeof AppGrnOemIndexRoute
  '/ims/transfers/': typeof AppImsTransfersIndexRoute
  '/sales/eway/': typeof AppSalesEwayIndexRoute
  '/sales/invoices/': typeof AppSalesInvoicesIndexRoute
  '/sales/payments/': typeof AppSalesPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/raise-ticket': typeof RaiseTicketRoute
  '/archive': typeof AppArchiveRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/masters': typeof AppMastersRouteWithChildren
  '/new': typeof AppNewRoute
  '/products': typeof AppProductsRoute
  '/records': typeof AppRecordsRoute
  '/reports': typeof AppReportsRoute
  '/amc/$id': typeof AppAmcIdRoute
  '/amc/new': typeof AppAmcNewRoute
  '/amc/oem': typeof AppAmcOemRoute
  '/amc/pm': typeof AppAmcPmRoute
  '/amc/settings': typeof AppAmcSettingsRoute
  '/challan/$id': typeof AppChallanIdRoute
  '/crm/bundles': typeof AppCrmBundlesRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/incentives': typeof AppCrmIncentivesRoute
  '/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/crm/settings': typeof AppCrmSettingsRoute
  '/gatepass/$id': typeof AppGatepassIdRoute
  '/grn/$id': typeof AppGrnIdRoute
  '/ims/audit': typeof AppImsAuditRoute
  '/ims/indent-history': typeof AppImsIndentHistoryRoute
  '/ims/oem-returns': typeof AppImsOemReturnsRoute
  '/ims/reports': typeof AppImsReportsRoute
  '/ims/reservations': typeof AppImsReservationsRoute
  '/ims/stock': typeof AppImsStockRoute
  '/ims/transactions': typeof AppImsTransactionsRoute
  '/indent/$id': typeof AppIndentIdRoute
  '/indent/new': typeof AppIndentNewRoute
  '/masters/customers': typeof AppMastersCustomersRoute
  '/masters/products': typeof AppMastersProductsRoute
  '/po/$id': typeof AppPoIdRoute
  '/po/new': typeof AppPoNewRoute
  '/po/settings': typeof AppPoSettingsRoute
  '/sales/quotations': typeof AppSalesQuotationsRoute
  '/sales/settings': typeof AppSalesSettingsRoute
  '/tickets/$id': typeof AppTicketsIdRoute
  '/tickets/dashboard': typeof AppTicketsDashboardRoute
  '/tickets/new': typeof AppTicketsNewRoute
  '/tickets/settings': typeof AppTicketsSettingsRoute
  '/tickets/templates': typeof AppTicketsTemplatesRoute
  '/amc': typeof AppAmcIndexRoute
  '/challan': typeof AppChallanIndexRoute
  '/crm': typeof AppCrmIndexRoute
  '/grn': typeof AppGrnIndexRoute
  '/ims': typeof AppImsIndexRoute
  '/indent': typeof AppIndentIndexRoute
  '/po': typeof AppPoIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
  '/challan/customer/new': typeof AppChallanCustomerNewRoute
  '/challan/oem/new': typeof AppChallanOemNewRoute
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
  '/grn/customer/new': typeof AppGrnCustomerNewRoute
  '/grn/general/new': typeof AppGrnGeneralNewRoute
  '/grn/oem/new': typeof AppGrnOemNewRoute
  '/ims/transfers/$id': typeof AppImsTransfersIdRoute
  '/ims/transfers/new': typeof AppImsTransfersNewRoute
  '/sales/invoices/$id': typeof AppSalesInvoicesIdRoute
  '/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/sales/payments/new': typeof AppSalesPaymentsNewRoute
  '/challan/customer': typeof AppChallanCustomerIndexRoute
  '/challan/oem': typeof AppChallanOemIndexRoute
  '/grn/customer': typeof AppGrnCustomerIndexRoute
  '/grn/general': typeof AppGrnGeneralIndexRoute
  '/grn/oem': typeof AppGrnOemIndexRoute
  '/ims/transfers': typeof AppImsTransfersIndexRoute
  '/sales/eway': typeof AppSalesEwayIndexRoute
  '/sales/invoices': typeof AppSalesInvoicesIndexRoute
  '/sales/payments': typeof AppSalesPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/raise-ticket': typeof RaiseTicketRoute
  '/_app/amc': typeof AppAmcRouteWithChildren
  '/_app/archive': typeof AppArchiveRoute
  '/_app/challan': typeof AppChallanRouteWithChildren
  '/_app/crm': typeof AppCrmRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/grn': typeof AppGrnRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/_app/ims': typeof AppImsRouteWithChildren
  '/_app/indent': typeof AppIndentRouteWithChildren
  '/_app/masters': typeof AppMastersRouteWithChildren
  '/_app/new': typeof AppNewRoute
  '/_app/po': typeof AppPoRouteWithChildren
  '/_app/products': typeof AppProductsRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_app/tickets': typeof AppTicketsRouteWithChildren
  '/_app/amc/$id': typeof AppAmcIdRoute
  '/_app/amc/new': typeof AppAmcNewRoute
  '/_app/amc/oem': typeof AppAmcOemRoute
  '/_app/amc/pm': typeof AppAmcPmRoute
  '/_app/amc/settings': typeof AppAmcSettingsRoute
  '/_app/challan/$id': typeof AppChallanIdRoute
  '/_app/challan/customer': typeof AppChallanCustomerRouteWithChildren
  '/_app/challan/oem': typeof AppChallanOemRouteWithChildren
  '/_app/crm/bundles': typeof AppCrmBundlesRoute
  '/_app/crm/customers': typeof AppCrmCustomersRoute
  '/_app/crm/incentives': typeof AppCrmIncentivesRoute
  '/_app/crm/leads': typeof AppCrmLeadsRouteWithChildren
  '/_app/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/_app/crm/settings': typeof AppCrmSettingsRoute
  '/_app/gatepass/$id': typeof AppGatepassIdRoute
  '/_app/grn/$id': typeof AppGrnIdRoute
  '/_app/grn/customer': typeof AppGrnCustomerRouteWithChildren
  '/_app/grn/general': typeof AppGrnGeneralRouteWithChildren
  '/_app/grn/oem': typeof AppGrnOemRouteWithChildren
  '/_app/ims/audit': typeof AppImsAuditRoute
  '/_app/ims/indent-history': typeof AppImsIndentHistoryRoute
  '/_app/ims/oem-returns': typeof AppImsOemReturnsRoute
  '/_app/ims/reports': typeof AppImsReportsRoute
  '/_app/ims/reservations': typeof AppImsReservationsRoute
  '/_app/ims/stock': typeof AppImsStockRoute
  '/_app/ims/transactions': typeof AppImsTransactionsRoute
  '/_app/ims/transfers': typeof AppImsTransfersRouteWithChildren
  '/_app/indent/$id': typeof AppIndentIdRoute
  '/_app/indent/new': typeof AppIndentNewRoute
  '/_app/masters/customers': typeof AppMastersCustomersRoute
  '/_app/masters/products': typeof AppMastersProductsRoute
  '/_app/po/$id': typeof AppPoIdRoute
  '/_app/po/new': typeof AppPoNewRoute
  '/_app/po/settings': typeof AppPoSettingsRoute
  '/_app/sales/quotations': typeof AppSalesQuotationsRoute
  '/_app/sales/settings': typeof AppSalesSettingsRoute
  '/_app/tickets/$id': typeof AppTicketsIdRoute
  '/_app/tickets/dashboard': typeof AppTicketsDashboardRoute
  '/_app/tickets/new': typeof AppTicketsNewRoute
  '/_app/tickets/settings': typeof AppTicketsSettingsRoute
  '/_app/tickets/templates': typeof AppTicketsTemplatesRoute
  '/_app/amc/': typeof AppAmcIndexRoute
  '/_app/challan/': typeof AppChallanIndexRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/grn/': typeof AppGrnIndexRoute
  '/_app/ims/': typeof AppImsIndexRoute
  '/_app/indent/': typeof AppIndentIndexRoute
  '/_app/po/': typeof AppPoIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
  '/_app/challan/customer/new': typeof AppChallanCustomerNewRoute
  '/_app/challan/oem/new': typeof AppChallanOemNewRoute
  '/_app/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/_app/crm/quotations/$id': typeof AppCrmQuotationsIdRoute
  '/_app/grn/customer/new': typeof AppGrnCustomerNewRoute
  '/_app/grn/general/new': typeof AppGrnGeneralNewRoute
  '/_app/grn/oem/new': typeof AppGrnOemNewRoute
  '/_app/ims/transfers/$id': typeof AppImsTransfersIdRoute
  '/_app/ims/transfers/new': typeof AppImsTransfersNewRoute
  '/_app/sales/invoices/$id': typeof AppSalesInvoicesIdRoute
  '/_app/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/_app/sales/payments/new': typeof AppSalesPaymentsNewRoute
  '/_app/challan/customer/': typeof AppChallanCustomerIndexRoute
  '/_app/challan/oem/': typeof AppChallanOemIndexRoute
  '/_app/grn/customer/': typeof AppGrnCustomerIndexRoute
  '/_app/grn/general/': typeof AppGrnGeneralIndexRoute
  '/_app/grn/oem/': typeof AppGrnOemIndexRoute
  '/_app/ims/transfers/': typeof AppImsTransfersIndexRoute
  '/_app/sales/eway/': typeof AppSalesEwayIndexRoute
  '/_app/sales/invoices/': typeof AppSalesInvoicesIndexRoute
  '/_app/sales/payments/': typeof AppSalesPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/raise-ticket'
    | '/amc'
    | '/archive'
    | '/challan'
    | '/crm'
    | '/dashboard'
    | '/grn'
    | '/import'
    | '/ims'
    | '/indent'
    | '/masters'
    | '/new'
    | '/po'
    | '/products'
    | '/records'
    | '/reports'
    | '/sales'
    | '/tickets'
    | '/amc/$id'
    | '/amc/new'
    | '/amc/oem'
    | '/amc/pm'
    | '/amc/settings'
    | '/challan/$id'
    | '/challan/customer'
    | '/challan/oem'
    | '/crm/bundles'
    | '/crm/customers'
    | '/crm/incentives'
    | '/crm/leads'
    | '/crm/quotations'
    | '/crm/settings'
    | '/gatepass/$id'
    | '/grn/$id'
    | '/grn/customer'
    | '/grn/general'
    | '/grn/oem'
    | '/ims/audit'
    | '/ims/indent-history'
    | '/ims/oem-returns'
    | '/ims/reports'
    | '/ims/reservations'
    | '/ims/stock'
    | '/ims/transactions'
    | '/ims/transfers'
    | '/indent/$id'
    | '/indent/new'
    | '/masters/customers'
    | '/masters/products'
    | '/po/$id'
    | '/po/new'
    | '/po/settings'
    | '/sales/quotations'
    | '/sales/settings'
    | '/tickets/$id'
    | '/tickets/dashboard'
    | '/tickets/new'
    | '/tickets/settings'
    | '/tickets/templates'
    | '/amc/'
    | '/challan/'
    | '/crm/'
    | '/grn/'
    | '/ims/'
    | '/indent/'
    | '/po/'
    | '/sales/'
    | '/tickets/'
    | '/challan/customer/new'
    | '/challan/oem/new'
    | '/crm/leads/$id'
    | '/crm/quotations/$id'
    | '/grn/customer/new'
    | '/grn/general/new'
    | '/grn/oem/new'
    | '/ims/transfers/$id'
    | '/ims/transfers/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/payments/new'
    | '/challan/customer/'
    | '/challan/oem/'
    | '/grn/customer/'
    | '/grn/general/'
    | '/grn/oem/'
    | '/ims/transfers/'
    | '/sales/eway/'
    | '/sales/invoices/'
    | '/sales/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/raise-ticket'
    | '/archive'
    | '/dashboard'
    | '/import'
    | '/masters'
    | '/new'
    | '/products'
    | '/records'
    | '/reports'
    | '/amc/$id'
    | '/amc/new'
    | '/amc/oem'
    | '/amc/pm'
    | '/amc/settings'
    | '/challan/$id'
    | '/crm/bundles'
    | '/crm/customers'
    | '/crm/incentives'
    | '/crm/leads'
    | '/crm/quotations'
    | '/crm/settings'
    | '/gatepass/$id'
    | '/grn/$id'
    | '/ims/audit'
    | '/ims/indent-history'
    | '/ims/oem-returns'
    | '/ims/reports'
    | '/ims/reservations'
    | '/ims/stock'
    | '/ims/transactions'
    | '/indent/$id'
    | '/indent/new'
    | '/masters/customers'
    | '/masters/products'
    | '/po/$id'
    | '/po/new'
    | '/po/settings'
    | '/sales/quotations'
    | '/sales/settings'
    | '/tickets/$id'
    | '/tickets/dashboard'
    | '/tickets/new'
    | '/tickets/settings'
    | '/tickets/templates'
    | '/amc'
    | '/challan'
    | '/crm'
    | '/grn'
    | '/ims'
    | '/indent'
    | '/po'
    | '/sales'
    | '/tickets'
    | '/challan/customer/new'
    | '/challan/oem/new'
    | '/crm/leads/$id'
    | '/crm/quotations/$id'
    | '/grn/customer/new'
    | '/grn/general/new'
    | '/grn/oem/new'
    | '/ims/transfers/$id'
    | '/ims/transfers/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/payments/new'
    | '/challan/customer'
    | '/challan/oem'
    | '/grn/customer'
    | '/grn/general'
    | '/grn/oem'
    | '/ims/transfers'
    | '/sales/eway'
    | '/sales/invoices'
    | '/sales/payments'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/raise-ticket'
    | '/_app/amc'
    | '/_app/archive'
    | '/_app/challan'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/grn'
    | '/_app/import'
    | '/_app/ims'
    | '/_app/indent'
    | '/_app/masters'
    | '/_app/new'
    | '/_app/po'
    | '/_app/products'
    | '/_app/records'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/tickets'
    | '/_app/amc/$id'
    | '/_app/amc/new'
    | '/_app/amc/oem'
    | '/_app/amc/pm'
    | '/_app/amc/settings'
    | '/_app/challan/$id'
    | '/_app/challan/customer'
    | '/_app/challan/oem'
    | '/_app/crm/bundles'
    | '/_app/crm/customers'
    | '/_app/crm/incentives'
    | '/_app/crm/leads'
    | '/_app/crm/quotations'
    | '/_app/crm/settings'
    | '/_app/gatepass/$id'
    | '/_app/grn/$id'
    | '/_app/grn/customer'
    | '/_app/grn/general'
    | '/_app/grn/oem'
    | '/_app/ims/audit'
    | '/_app/ims/indent-history'
    | '/_app/ims/oem-returns'
    | '/_app/ims/reports'
    | '/_app/ims/reservations'
    | '/_app/ims/stock'
    | '/_app/ims/transactions'
    | '/_app/ims/transfers'
    | '/_app/indent/$id'
    | '/_app/indent/new'
    | '/_app/masters/customers'
    | '/_app/masters/products'
    | '/_app/po/$id'
    | '/_app/po/new'
    | '/_app/po/settings'
    | '/_app/sales/quotations'
    | '/_app/sales/settings'
    | '/_app/tickets/$id'
    | '/_app/tickets/dashboard'
    | '/_app/tickets/new'
    | '/_app/tickets/settings'
    | '/_app/tickets/templates'
    | '/_app/amc/'
    | '/_app/challan/'
    | '/_app/crm/'
    | '/_app/grn/'
    | '/_app/ims/'
    | '/_app/indent/'
    | '/_app/po/'
    | '/_app/sales/'
    | '/_app/tickets/'
    | '/_app/challan/customer/new'
    | '/_app/challan/oem/new'
    | '/_app/crm/leads/$id'
    | '/_app/crm/quotations/$id'
    | '/_app/grn/customer/new'
    | '/_app/grn/general/new'
    | '/_app/grn/oem/new'
    | '/_app/ims/transfers/$id'
    | '/_app/ims/transfers/new'
    | '/_app/sales/invoices/$id'
    | '/_app/sales/invoices/new'
    | '/_app/sales/payments/new'
    | '/_app/challan/customer/'
    | '/_app/challan/oem/'
    | '/_app/grn/customer/'
    | '/_app/grn/general/'
    | '/_app/grn/oem/'
    | '/_app/ims/transfers/'
    | '/_app/sales/eway/'
    | '/_app/sales/invoices/'
    | '/_app/sales/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RaiseTicketRoute: typeof RaiseTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raise-ticket': {
      id: '/raise-ticket'
      path: '/raise-ticket'
      fullPath: '/raise-ticket'
      preLoaderRoute: typeof RaiseTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/po': {
      id: '/_app/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof AppPoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indent': {
      id: '/_app/indent'
      path: '/indent'
      fullPath: '/indent'
      preLoaderRoute: typeof AppIndentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ims': {
      id: '/_app/ims'
      path: '/ims'
      fullPath: '/ims'
      preLoaderRoute: typeof AppImsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grn': {
      id: '/_app/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof AppGrnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challan': {
      id: '/_app/challan'
      path: '/challan'
      fullPath: '/challan'
      preLoaderRoute: typeof AppChallanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/amc': {
      id: '/_app/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AppAmcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/po/': {
      id: '/_app/po/'
      path: '/'
      fullPath: '/po/'
      preLoaderRoute: typeof AppPoIndexRouteImport
      parentRoute: typeof AppPoRoute
    }
    '/_app/indent/': {
      id: '/_app/indent/'
      path: '/'
      fullPath: '/indent/'
      preLoaderRoute: typeof AppIndentIndexRouteImport
      parentRoute: typeof AppIndentRoute
    }
    '/_app/ims/': {
      id: '/_app/ims/'
      path: '/'
      fullPath: '/ims/'
      preLoaderRoute: typeof AppImsIndexRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/grn/': {
      id: '/_app/grn/'
      path: '/'
      fullPath: '/grn/'
      preLoaderRoute: typeof AppGrnIndexRouteImport
      parentRoute: typeof AppGrnRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/challan/': {
      id: '/_app/challan/'
      path: '/'
      fullPath: '/challan/'
      preLoaderRoute: typeof AppChallanIndexRouteImport
      parentRoute: typeof AppChallanRoute
    }
    '/_app/amc/': {
      id: '/_app/amc/'
      path: '/'
      fullPath: '/amc/'
      preLoaderRoute: typeof AppAmcIndexRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/tickets/templates': {
      id: '/_app/tickets/templates'
      path: '/templates'
      fullPath: '/tickets/templates'
      preLoaderRoute: typeof AppTicketsTemplatesRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/settings': {
      id: '/_app/tickets/settings'
      path: '/settings'
      fullPath: '/tickets/settings'
      preLoaderRoute: typeof AppTicketsSettingsRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/new': {
      id: '/_app/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AppTicketsNewRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/dashboard': {
      id: '/_app/tickets/dashboard'
      path: '/dashboard'
      fullPath: '/tickets/dashboard'
      preLoaderRoute: typeof AppTicketsDashboardRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/$id': {
      id: '/_app/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AppTicketsIdRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/sales/settings': {
      id: '/_app/sales/settings'
      path: '/settings'
      fullPath: '/sales/settings'
      preLoaderRoute: typeof AppSalesSettingsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/quotations': {
      id: '/_app/sales/quotations'
      path: '/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof AppSalesQuotationsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/po/settings': {
      id: '/_app/po/settings'
      path: '/settings'
      fullPath: '/po/settings'
      preLoaderRoute: typeof AppPoSettingsRouteImport
      parentRoute: typeof AppPoRoute
    }
    '/_app/po/new': {
      id: '/_app/po/new'
      path: '/new'
      fullPath: '/po/new'
      preLoaderRoute: typeof AppPoNewRouteImport
      parentRoute: typeof AppPoRoute
    }
    '/_app/po/$id': {
      id: '/_app/po/$id'
      path: '/$id'
      fullPath: '/po/$id'
      preLoaderRoute: typeof AppPoIdRouteImport
      parentRoute: typeof AppPoRoute
    }
    '/_app/masters/products': {
      id: '/_app/masters/products'
      path: '/products'
      fullPath: '/masters/products'
      preLoaderRoute: typeof AppMastersProductsRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/masters/customers': {
      id: '/_app/masters/customers'
      path: '/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof AppMastersCustomersRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/indent/new': {
      id: '/_app/indent/new'
      path: '/new'
      fullPath: '/indent/new'
      preLoaderRoute: typeof AppIndentNewRouteImport
      parentRoute: typeof AppIndentRoute
    }
    '/_app/indent/$id': {
      id: '/_app/indent/$id'
      path: '/$id'
      fullPath: '/indent/$id'
      preLoaderRoute: typeof AppIndentIdRouteImport
      parentRoute: typeof AppIndentRoute
    }
    '/_app/ims/transfers': {
      id: '/_app/ims/transfers'
      path: '/transfers'
      fullPath: '/ims/transfers'
      preLoaderRoute: typeof AppImsTransfersRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/transactions': {
      id: '/_app/ims/transactions'
      path: '/transactions'
      fullPath: '/ims/transactions'
      preLoaderRoute: typeof AppImsTransactionsRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/stock': {
      id: '/_app/ims/stock'
      path: '/stock'
      fullPath: '/ims/stock'
      preLoaderRoute: typeof AppImsStockRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/reservations': {
      id: '/_app/ims/reservations'
      path: '/reservations'
      fullPath: '/ims/reservations'
      preLoaderRoute: typeof AppImsReservationsRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/reports': {
      id: '/_app/ims/reports'
      path: '/reports'
      fullPath: '/ims/reports'
      preLoaderRoute: typeof AppImsReportsRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/oem-returns': {
      id: '/_app/ims/oem-returns'
      path: '/oem-returns'
      fullPath: '/ims/oem-returns'
      preLoaderRoute: typeof AppImsOemReturnsRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/indent-history': {
      id: '/_app/ims/indent-history'
      path: '/indent-history'
      fullPath: '/ims/indent-history'
      preLoaderRoute: typeof AppImsIndentHistoryRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/ims/audit': {
      id: '/_app/ims/audit'
      path: '/audit'
      fullPath: '/ims/audit'
      preLoaderRoute: typeof AppImsAuditRouteImport
      parentRoute: typeof AppImsRoute
    }
    '/_app/grn/oem': {
      id: '/_app/grn/oem'
      path: '/oem'
      fullPath: '/grn/oem'
      preLoaderRoute: typeof AppGrnOemRouteImport
      parentRoute: typeof AppGrnRoute
    }
    '/_app/grn/general': {
      id: '/_app/grn/general'
      path: '/general'
      fullPath: '/grn/general'
      preLoaderRoute: typeof AppGrnGeneralRouteImport
      parentRoute: typeof AppGrnRoute
    }
    '/_app/grn/customer': {
      id: '/_app/grn/customer'
      path: '/customer'
      fullPath: '/grn/customer'
      preLoaderRoute: typeof AppGrnCustomerRouteImport
      parentRoute: typeof AppGrnRoute
    }
    '/_app/grn/$id': {
      id: '/_app/grn/$id'
      path: '/$id'
      fullPath: '/grn/$id'
      preLoaderRoute: typeof AppGrnIdRouteImport
      parentRoute: typeof AppGrnRoute
    }
    '/_app/gatepass/$id': {
      id: '/_app/gatepass/$id'
      path: '/gatepass/$id'
      fullPath: '/gatepass/$id'
      preLoaderRoute: typeof AppGatepassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/settings': {
      id: '/_app/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AppCrmSettingsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/quotations': {
      id: '/_app/crm/quotations'
      path: '/quotations'
      fullPath: '/crm/quotations'
      preLoaderRoute: typeof AppCrmQuotationsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/leads': {
      id: '/_app/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/incentives': {
      id: '/_app/crm/incentives'
      path: '/incentives'
      fullPath: '/crm/incentives'
      preLoaderRoute: typeof AppCrmIncentivesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/customers': {
      id: '/_app/crm/customers'
      path: '/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/bundles': {
      id: '/_app/crm/bundles'
      path: '/bundles'
      fullPath: '/crm/bundles'
      preLoaderRoute: typeof AppCrmBundlesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/challan/oem': {
      id: '/_app/challan/oem'
      path: '/oem'
      fullPath: '/challan/oem'
      preLoaderRoute: typeof AppChallanOemRouteImport
      parentRoute: typeof AppChallanRoute
    }
    '/_app/challan/customer': {
      id: '/_app/challan/customer'
      path: '/customer'
      fullPath: '/challan/customer'
      preLoaderRoute: typeof AppChallanCustomerRouteImport
      parentRoute: typeof AppChallanRoute
    }
    '/_app/challan/$id': {
      id: '/_app/challan/$id'
      path: '/$id'
      fullPath: '/challan/$id'
      preLoaderRoute: typeof AppChallanIdRouteImport
      parentRoute: typeof AppChallanRoute
    }
    '/_app/amc/settings': {
      id: '/_app/amc/settings'
      path: '/settings'
      fullPath: '/amc/settings'
      preLoaderRoute: typeof AppAmcSettingsRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/pm': {
      id: '/_app/amc/pm'
      path: '/pm'
      fullPath: '/amc/pm'
      preLoaderRoute: typeof AppAmcPmRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/oem': {
      id: '/_app/amc/oem'
      path: '/oem'
      fullPath: '/amc/oem'
      preLoaderRoute: typeof AppAmcOemRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/new': {
      id: '/_app/amc/new'
      path: '/new'
      fullPath: '/amc/new'
      preLoaderRoute: typeof AppAmcNewRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/amc/$id': {
      id: '/_app/amc/$id'
      path: '/$id'
      fullPath: '/amc/$id'
      preLoaderRoute: typeof AppAmcIdRouteImport
      parentRoute: typeof AppAmcRoute
    }
    '/_app/sales/payments/': {
      id: '/_app/sales/payments/'
      path: '/payments'
      fullPath: '/sales/payments/'
      preLoaderRoute: typeof AppSalesPaymentsIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/invoices/': {
      id: '/_app/sales/invoices/'
      path: '/invoices'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof AppSalesInvoicesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/eway/': {
      id: '/_app/sales/eway/'
      path: '/eway'
      fullPath: '/sales/eway/'
      preLoaderRoute: typeof AppSalesEwayIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/ims/transfers/': {
      id: '/_app/ims/transfers/'
      path: '/'
      fullPath: '/ims/transfers/'
      preLoaderRoute: typeof AppImsTransfersIndexRouteImport
      parentRoute: typeof AppImsTransfersRoute
    }
    '/_app/grn/oem/': {
      id: '/_app/grn/oem/'
      path: '/'
      fullPath: '/grn/oem/'
      preLoaderRoute: typeof AppGrnOemIndexRouteImport
      parentRoute: typeof AppGrnOemRoute
    }
    '/_app/grn/general/': {
      id: '/_app/grn/general/'
      path: '/'
      fullPath: '/grn/general/'
      preLoaderRoute: typeof AppGrnGeneralIndexRouteImport
      parentRoute: typeof AppGrnGeneralRoute
    }
    '/_app/grn/customer/': {
      id: '/_app/grn/customer/'
      path: '/'
      fullPath: '/grn/customer/'
      preLoaderRoute: typeof AppGrnCustomerIndexRouteImport
      parentRoute: typeof AppGrnCustomerRoute
    }
    '/_app/challan/oem/': {
      id: '/_app/challan/oem/'
      path: '/'
      fullPath: '/challan/oem/'
      preLoaderRoute: typeof AppChallanOemIndexRouteImport
      parentRoute: typeof AppChallanOemRoute
    }
    '/_app/challan/customer/': {
      id: '/_app/challan/customer/'
      path: '/'
      fullPath: '/challan/customer/'
      preLoaderRoute: typeof AppChallanCustomerIndexRouteImport
      parentRoute: typeof AppChallanCustomerRoute
    }
    '/_app/sales/payments/new': {
      id: '/_app/sales/payments/new'
      path: '/payments/new'
      fullPath: '/sales/payments/new'
      preLoaderRoute: typeof AppSalesPaymentsNewRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/invoices/new': {
      id: '/_app/sales/invoices/new'
      path: '/invoices/new'
      fullPath: '/sales/invoices/new'
      preLoaderRoute: typeof AppSalesInvoicesNewRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/invoices/$id': {
      id: '/_app/sales/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/sales/invoices/$id'
      preLoaderRoute: typeof AppSalesInvoicesIdRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/ims/transfers/new': {
      id: '/_app/ims/transfers/new'
      path: '/new'
      fullPath: '/ims/transfers/new'
      preLoaderRoute: typeof AppImsTransfersNewRouteImport
      parentRoute: typeof AppImsTransfersRoute
    }
    '/_app/ims/transfers/$id': {
      id: '/_app/ims/transfers/$id'
      path: '/$id'
      fullPath: '/ims/transfers/$id'
      preLoaderRoute: typeof AppImsTransfersIdRouteImport
      parentRoute: typeof AppImsTransfersRoute
    }
    '/_app/grn/oem/new': {
      id: '/_app/grn/oem/new'
      path: '/new'
      fullPath: '/grn/oem/new'
      preLoaderRoute: typeof AppGrnOemNewRouteImport
      parentRoute: typeof AppGrnOemRoute
    }
    '/_app/grn/general/new': {
      id: '/_app/grn/general/new'
      path: '/new'
      fullPath: '/grn/general/new'
      preLoaderRoute: typeof AppGrnGeneralNewRouteImport
      parentRoute: typeof AppGrnGeneralRoute
    }
    '/_app/grn/customer/new': {
      id: '/_app/grn/customer/new'
      path: '/new'
      fullPath: '/grn/customer/new'
      preLoaderRoute: typeof AppGrnCustomerNewRouteImport
      parentRoute: typeof AppGrnCustomerRoute
    }
    '/_app/crm/quotations/$id': {
      id: '/_app/crm/quotations/$id'
      path: '/$id'
      fullPath: '/crm/quotations/$id'
      preLoaderRoute: typeof AppCrmQuotationsIdRouteImport
      parentRoute: typeof AppCrmQuotationsRoute
    }
    '/_app/crm/leads/$id': {
      id: '/_app/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AppCrmLeadsIdRouteImport
      parentRoute: typeof AppCrmLeadsRoute
    }
    '/_app/challan/oem/new': {
      id: '/_app/challan/oem/new'
      path: '/new'
      fullPath: '/challan/oem/new'
      preLoaderRoute: typeof AppChallanOemNewRouteImport
      parentRoute: typeof AppChallanOemRoute
    }
    '/_app/challan/customer/new': {
      id: '/_app/challan/customer/new'
      path: '/new'
      fullPath: '/challan/customer/new'
      preLoaderRoute: typeof AppChallanCustomerNewRouteImport
      parentRoute: typeof AppChallanCustomerRoute
    }
  }
}

interface AppAmcRouteChildren {
  AppAmcIdRoute: typeof AppAmcIdRoute
  AppAmcNewRoute: typeof AppAmcNewRoute
  AppAmcOemRoute: typeof AppAmcOemRoute
  AppAmcPmRoute: typeof AppAmcPmRoute
  AppAmcSettingsRoute: typeof AppAmcSettingsRoute
  AppAmcIndexRoute: typeof AppAmcIndexRoute
}

const AppAmcRouteChildren: AppAmcRouteChildren = {
  AppAmcIdRoute: AppAmcIdRoute,
  AppAmcNewRoute: AppAmcNewRoute,
  AppAmcOemRoute: AppAmcOemRoute,
  AppAmcPmRoute: AppAmcPmRoute,
  AppAmcSettingsRoute: AppAmcSettingsRoute,
  AppAmcIndexRoute: AppAmcIndexRoute,
}

const AppAmcRouteWithChildren =
  AppAmcRoute._addFileChildren(AppAmcRouteChildren)

interface AppChallanCustomerRouteChildren {
  AppChallanCustomerNewRoute: typeof AppChallanCustomerNewRoute
  AppChallanCustomerIndexRoute: typeof AppChallanCustomerIndexRoute
}

const AppChallanCustomerRouteChildren: AppChallanCustomerRouteChildren = {
  AppChallanCustomerNewRoute: AppChallanCustomerNewRoute,
  AppChallanCustomerIndexRoute: AppChallanCustomerIndexRoute,
}

const AppChallanCustomerRouteWithChildren =
  AppChallanCustomerRoute._addFileChildren(AppChallanCustomerRouteChildren)

interface AppChallanOemRouteChildren {
  AppChallanOemNewRoute: typeof AppChallanOemNewRoute
  AppChallanOemIndexRoute: typeof AppChallanOemIndexRoute
}

const AppChallanOemRouteChildren: AppChallanOemRouteChildren = {
  AppChallanOemNewRoute: AppChallanOemNewRoute,
  AppChallanOemIndexRoute: AppChallanOemIndexRoute,
}

const AppChallanOemRouteWithChildren = AppChallanOemRoute._addFileChildren(
  AppChallanOemRouteChildren,
)

interface AppChallanRouteChildren {
  AppChallanIdRoute: typeof AppChallanIdRoute
  AppChallanCustomerRoute: typeof AppChallanCustomerRouteWithChildren
  AppChallanOemRoute: typeof AppChallanOemRouteWithChildren
  AppChallanIndexRoute: typeof AppChallanIndexRoute
}

const AppChallanRouteChildren: AppChallanRouteChildren = {
  AppChallanIdRoute: AppChallanIdRoute,
  AppChallanCustomerRoute: AppChallanCustomerRouteWithChildren,
  AppChallanOemRoute: AppChallanOemRouteWithChildren,
  AppChallanIndexRoute: AppChallanIndexRoute,
}

const AppChallanRouteWithChildren = AppChallanRoute._addFileChildren(
  AppChallanRouteChildren,
)

interface AppCrmLeadsRouteChildren {
  AppCrmLeadsIdRoute: typeof AppCrmLeadsIdRoute
}

const AppCrmLeadsRouteChildren: AppCrmLeadsRouteChildren = {
  AppCrmLeadsIdRoute: AppCrmLeadsIdRoute,
}

const AppCrmLeadsRouteWithChildren = AppCrmLeadsRoute._addFileChildren(
  AppCrmLeadsRouteChildren,
)

interface AppCrmQuotationsRouteChildren {
  AppCrmQuotationsIdRoute: typeof AppCrmQuotationsIdRoute
}

const AppCrmQuotationsRouteChildren: AppCrmQuotationsRouteChildren = {
  AppCrmQuotationsIdRoute: AppCrmQuotationsIdRoute,
}

const AppCrmQuotationsRouteWithChildren =
  AppCrmQuotationsRoute._addFileChildren(AppCrmQuotationsRouteChildren)

interface AppCrmRouteChildren {
  AppCrmBundlesRoute: typeof AppCrmBundlesRoute
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmIncentivesRoute: typeof AppCrmIncentivesRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRouteWithChildren
  AppCrmQuotationsRoute: typeof AppCrmQuotationsRouteWithChildren
  AppCrmSettingsRoute: typeof AppCrmSettingsRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmBundlesRoute: AppCrmBundlesRoute,
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmIncentivesRoute: AppCrmIncentivesRoute,
  AppCrmLeadsRoute: AppCrmLeadsRouteWithChildren,
  AppCrmQuotationsRoute: AppCrmQuotationsRouteWithChildren,
  AppCrmSettingsRoute: AppCrmSettingsRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppGrnCustomerRouteChildren {
  AppGrnCustomerNewRoute: typeof AppGrnCustomerNewRoute
  AppGrnCustomerIndexRoute: typeof AppGrnCustomerIndexRoute
}

const AppGrnCustomerRouteChildren: AppGrnCustomerRouteChildren = {
  AppGrnCustomerNewRoute: AppGrnCustomerNewRoute,
  AppGrnCustomerIndexRoute: AppGrnCustomerIndexRoute,
}

const AppGrnCustomerRouteWithChildren = AppGrnCustomerRoute._addFileChildren(
  AppGrnCustomerRouteChildren,
)

interface AppGrnGeneralRouteChildren {
  AppGrnGeneralNewRoute: typeof AppGrnGeneralNewRoute
  AppGrnGeneralIndexRoute: typeof AppGrnGeneralIndexRoute
}

const AppGrnGeneralRouteChildren: AppGrnGeneralRouteChildren = {
  AppGrnGeneralNewRoute: AppGrnGeneralNewRoute,
  AppGrnGeneralIndexRoute: AppGrnGeneralIndexRoute,
}

const AppGrnGeneralRouteWithChildren = AppGrnGeneralRoute._addFileChildren(
  AppGrnGeneralRouteChildren,
)

interface AppGrnOemRouteChildren {
  AppGrnOemNewRoute: typeof AppGrnOemNewRoute
  AppGrnOemIndexRoute: typeof AppGrnOemIndexRoute
}

const AppGrnOemRouteChildren: AppGrnOemRouteChildren = {
  AppGrnOemNewRoute: AppGrnOemNewRoute,
  AppGrnOemIndexRoute: AppGrnOemIndexRoute,
}

const AppGrnOemRouteWithChildren = AppGrnOemRoute._addFileChildren(
  AppGrnOemRouteChildren,
)

interface AppGrnRouteChildren {
  AppGrnIdRoute: typeof AppGrnIdRoute
  AppGrnCustomerRoute: typeof AppGrnCustomerRouteWithChildren
  AppGrnGeneralRoute: typeof AppGrnGeneralRouteWithChildren
  AppGrnOemRoute: typeof AppGrnOemRouteWithChildren
  AppGrnIndexRoute: typeof AppGrnIndexRoute
}

const AppGrnRouteChildren: AppGrnRouteChildren = {
  AppGrnIdRoute: AppGrnIdRoute,
  AppGrnCustomerRoute: AppGrnCustomerRouteWithChildren,
  AppGrnGeneralRoute: AppGrnGeneralRouteWithChildren,
  AppGrnOemRoute: AppGrnOemRouteWithChildren,
  AppGrnIndexRoute: AppGrnIndexRoute,
}

const AppGrnRouteWithChildren =
  AppGrnRoute._addFileChildren(AppGrnRouteChildren)

interface AppImsTransfersRouteChildren {
  AppImsTransfersIdRoute: typeof AppImsTransfersIdRoute
  AppImsTransfersNewRoute: typeof AppImsTransfersNewRoute
  AppImsTransfersIndexRoute: typeof AppImsTransfersIndexRoute
}

const AppImsTransfersRouteChildren: AppImsTransfersRouteChildren = {
  AppImsTransfersIdRoute: AppImsTransfersIdRoute,
  AppImsTransfersNewRoute: AppImsTransfersNewRoute,
  AppImsTransfersIndexRoute: AppImsTransfersIndexRoute,
}

const AppImsTransfersRouteWithChildren = AppImsTransfersRoute._addFileChildren(
  AppImsTransfersRouteChildren,
)

interface AppImsRouteChildren {
  AppImsAuditRoute: typeof AppImsAuditRoute
  AppImsIndentHistoryRoute: typeof AppImsIndentHistoryRoute
  AppImsOemReturnsRoute: typeof AppImsOemReturnsRoute
  AppImsReportsRoute: typeof AppImsReportsRoute
  AppImsReservationsRoute: typeof AppImsReservationsRoute
  AppImsStockRoute: typeof AppImsStockRoute
  AppImsTransactionsRoute: typeof AppImsTransactionsRoute
  AppImsTransfersRoute: typeof AppImsTransfersRouteWithChildren
  AppImsIndexRoute: typeof AppImsIndexRoute
}

const AppImsRouteChildren: AppImsRouteChildren = {
  AppImsAuditRoute: AppImsAuditRoute,
  AppImsIndentHistoryRoute: AppImsIndentHistoryRoute,
  AppImsOemReturnsRoute: AppImsOemReturnsRoute,
  AppImsReportsRoute: AppImsReportsRoute,
  AppImsReservationsRoute: AppImsReservationsRoute,
  AppImsStockRoute: AppImsStockRoute,
  AppImsTransactionsRoute: AppImsTransactionsRoute,
  AppImsTransfersRoute: AppImsTransfersRouteWithChildren,
  AppImsIndexRoute: AppImsIndexRoute,
}

const AppImsRouteWithChildren =
  AppImsRoute._addFileChildren(AppImsRouteChildren)

interface AppIndentRouteChildren {
  AppIndentIdRoute: typeof AppIndentIdRoute
  AppIndentNewRoute: typeof AppIndentNewRoute
  AppIndentIndexRoute: typeof AppIndentIndexRoute
}

const AppIndentRouteChildren: AppIndentRouteChildren = {
  AppIndentIdRoute: AppIndentIdRoute,
  AppIndentNewRoute: AppIndentNewRoute,
  AppIndentIndexRoute: AppIndentIndexRoute,
}

const AppIndentRouteWithChildren = AppIndentRoute._addFileChildren(
  AppIndentRouteChildren,
)

interface AppMastersRouteChildren {
  AppMastersCustomersRoute: typeof AppMastersCustomersRoute
  AppMastersProductsRoute: typeof AppMastersProductsRoute
}

const AppMastersRouteChildren: AppMastersRouteChildren = {
  AppMastersCustomersRoute: AppMastersCustomersRoute,
  AppMastersProductsRoute: AppMastersProductsRoute,
}

const AppMastersRouteWithChildren = AppMastersRoute._addFileChildren(
  AppMastersRouteChildren,
)

interface AppPoRouteChildren {
  AppPoIdRoute: typeof AppPoIdRoute
  AppPoNewRoute: typeof AppPoNewRoute
  AppPoSettingsRoute: typeof AppPoSettingsRoute
  AppPoIndexRoute: typeof AppPoIndexRoute
}

const AppPoRouteChildren: AppPoRouteChildren = {
  AppPoIdRoute: AppPoIdRoute,
  AppPoNewRoute: AppPoNewRoute,
  AppPoSettingsRoute: AppPoSettingsRoute,
  AppPoIndexRoute: AppPoIndexRoute,
}

const AppPoRouteWithChildren = AppPoRoute._addFileChildren(AppPoRouteChildren)

interface AppSalesRouteChildren {
  AppSalesQuotationsRoute: typeof AppSalesQuotationsRoute
  AppSalesSettingsRoute: typeof AppSalesSettingsRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSalesInvoicesIdRoute: typeof AppSalesInvoicesIdRoute
  AppSalesInvoicesNewRoute: typeof AppSalesInvoicesNewRoute
  AppSalesPaymentsNewRoute: typeof AppSalesPaymentsNewRoute
  AppSalesEwayIndexRoute: typeof AppSalesEwayIndexRoute
  AppSalesInvoicesIndexRoute: typeof AppSalesInvoicesIndexRoute
  AppSalesPaymentsIndexRoute: typeof AppSalesPaymentsIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesQuotationsRoute: AppSalesQuotationsRoute,
  AppSalesSettingsRoute: AppSalesSettingsRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSalesInvoicesIdRoute: AppSalesInvoicesIdRoute,
  AppSalesInvoicesNewRoute: AppSalesInvoicesNewRoute,
  AppSalesPaymentsNewRoute: AppSalesPaymentsNewRoute,
  AppSalesEwayIndexRoute: AppSalesEwayIndexRoute,
  AppSalesInvoicesIndexRoute: AppSalesInvoicesIndexRoute,
  AppSalesPaymentsIndexRoute: AppSalesPaymentsIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppTicketsRouteChildren {
  AppTicketsIdRoute: typeof AppTicketsIdRoute
  AppTicketsDashboardRoute: typeof AppTicketsDashboardRoute
  AppTicketsNewRoute: typeof AppTicketsNewRoute
  AppTicketsSettingsRoute: typeof AppTicketsSettingsRoute
  AppTicketsTemplatesRoute: typeof AppTicketsTemplatesRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsIdRoute: AppTicketsIdRoute,
  AppTicketsDashboardRoute: AppTicketsDashboardRoute,
  AppTicketsNewRoute: AppTicketsNewRoute,
  AppTicketsSettingsRoute: AppTicketsSettingsRoute,
  AppTicketsTemplatesRoute: AppTicketsTemplatesRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppRouteChildren {
  AppAmcRoute: typeof AppAmcRouteWithChildren
  AppArchiveRoute: typeof AppArchiveRoute
  AppChallanRoute: typeof AppChallanRouteWithChildren
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppGrnRoute: typeof AppGrnRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppImsRoute: typeof AppImsRouteWithChildren
  AppIndentRoute: typeof AppIndentRouteWithChildren
  AppMastersRoute: typeof AppMastersRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppPoRoute: typeof AppPoRouteWithChildren
  AppProductsRoute: typeof AppProductsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppGatepassIdRoute: typeof AppGatepassIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmcRoute: AppAmcRouteWithChildren,
  AppArchiveRoute: AppArchiveRoute,
  AppChallanRoute: AppChallanRouteWithChildren,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppGrnRoute: AppGrnRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppImsRoute: AppImsRouteWithChildren,
  AppIndentRoute: AppIndentRouteWithChildren,
  AppMastersRoute: AppMastersRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppPoRoute: AppPoRouteWithChildren,
  AppProductsRoute: AppProductsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppGatepassIdRoute: AppGatepassIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RaiseTicketRoute: RaiseTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
