// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest, setResponseStatus } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import { evaluateAccountGate } from "@/lib/account-gate";
import type { Database } from "./types";

export type AuthGateError = Error & { statusCode: number; code: string };

/**
 * Build a 401 for the server-fn transport.
 *
 * It must be a real `Error` instance: the client RPC fetcher only *throws* a
 * serialized payload when it deserializes to an Error — a plain object would be
 * returned to the caller as if the call had succeeded. Extra own-properties
 * (`statusCode`, `code`) survive serialization, so callers can branch on them.
 */
function unauthorized(message: string, code: string): AuthGateError {
  const err = new Error(message) as AuthGateError;
  err.statusCode = 401;
  err.code = code;
  try {
    setResponseStatus(401);
  } catch {
    // Not inside a request scope (e.g. direct unit call) — the thrown
    // statusCode still carries the intent.
  }
  return err;
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    const userId = data.claims.sub;

    // Account gate data (forced password change / account status). Read with the
    // service-role client on purpose: it is unaffected by RLS hardening on
    // app_users, so the gate cannot be silently disabled by a policy change.
    // Resolved here (once per request) but *enforced* by `requireActiveUser`, so
    // the password-change and profile server fns stay reachable while a change
    // is pending.
    let mustChangePassword = false;
    let appUserStatus: string | null = null;
    try {
      const { supabaseAdmin } = await import("./client.server");
      const { data: appUser, error: appUserError } = await supabaseAdmin
        .from("app_users")
        .select("status,must_change_password")
        .eq("user_id", userId)
        .maybeSingle();
      if (appUserError) {
        console.error("[auth] could not read app_users gate row:", appUserError.message);
      } else if (appUser) {
        mustChangePassword = !!appUser.must_change_password;
        appUserStatus = appUser.status ?? null;
      }
    } catch (e) {
      console.error("[auth] app_users gate lookup failed (failing CLOSED):", e instanceof Error ? e.message : e);
      // Fail CLOSED: the gate lookup is a security control. A failed lookup must
      // NOT silently allow access — re-throw so the request is rejected instead
      // of proceeding with default-allow. Callers (requireActiveUser / the
      // server fn) get a 500/401 rather than an unauthenticated pass-through.
      throw e instanceof Error ? e : new Error("[auth] app_users gate lookup failed");
    }

    return next({
      context: {
        supabase,
        userId,
        claims: data.claims,
        mustChangePassword,
        appUserStatus,
      },
    });
  },
);

/**
 * Server-side enforcement of the forced-password-change and account-status
 * policies. Apply this to every authenticated server fn *except* the two that a
 * locked-out user legitimately needs: `changeOwnPassword` and `getMyProfile`.
 *
 * Depends on `requireSupabaseAuth`, so it can be used alone or alongside it
 * (TanStack de-duplicates middleware by identity — auth still runs once).
 */
export const requireActiveUser = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const denial = evaluateAccountGate({
      mustChangePassword: context.mustChangePassword,
      status: context.appUserStatus,
    });
    if (denial) throw unauthorized(denial.message, denial.code);
    return next();
  });
